Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -19,6 +19,15 @@ runs:
 
     - shell: bash
       run: docker pull ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }}
+    
+    - shell: bash
+      run: |
+        bash <(curl https://getvcn.codenotary.com -L)
+        state="$(vcn authenticate --org home-assistant.io --output json ${{ inputs.source }} | jq '.verification.status // 0')"
+        if [[ "${state}" != "0" ]]; then
+          echo "Invalid signature!"
+          exit 1
+        fi
 
     - shell: bash
       id: builder
