Fix CAS login (#117)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -16,7 +16,7 @@ runs:
           input="latest"
         fi
         echo "::set-output name=version::${input}"
-    
+
     - uses: home-assistant/actions/helpers/cas@master
 
     - shell: bash
@@ -25,10 +25,15 @@ runs:
 
     - shell: bash
       run: |
-        if ! CAS_API_KEY= cas authenticate --silent --signerID notary@home-assistant.io docker://ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }}; then
-          echo "Invalid signature!"
-          exit 1
-        fi
+        for j in {1..3}; do
+          if CAS_API_KEY= cas authenticate --silent --signerID notary@home-assistant.io docker://ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }}; then
+            exit 0
+          fi
+          sleep 5
+        done
+
+        echo "Invalid signature!"
+        exit 1
 
     - shell: bash
       id: builder
